name: Generate files_info.json

on:
  push:
    paths:
      - 'files/**'  # Trigger only when files change in the files directory
    branches:
      - main  # Replace with the branch where users push changes
  workflow_dispatch:

jobs:
  generate_files_info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install natsort

      - name: Run Python script
        run: python generate_files_info.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet files_info.json; then
            echo "No changes to commit"
            echo "changed=false" >> $GITHUB_ENV
          else
            echo "Changes detected"
            echo "changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.changed == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add files_info.json
          git commit -m "Generate files_info.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
